[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "semgem"
version = "0.1.0"
description = "Semantic layer generator for SBML genome-scale metabolic models"
requires-python = ">=3.11"
dependencies = [
    "cobra",
    "pandas",
    "typer"
]

[project.scripts]
semgem = "semgem.cli:app"

[tool.setuptools.packages.find]
include = ["semgem*"]
exclude = ["models*", "outputs*", "tests*", "docs*"]

[tool.setuptools.package-data]
semgem = [
    "database/*.sql",
    "resources/*.toml"
]